blueprint:
  name: LLM Script for Lights voice requests
  source_url: https://github.com/BrendanxP/HA-Blueprints/edit/main/llm_lights_script.yaml
  description: |
    This script controls ALL lights via voice. Use for single lights, areas, floors.
    
    Parameters: action, target_type (entity/area/floor), target_name, brightness_pct, rgb_color, color_temp_kelvin, etc.
    
    Use this tool whenever user requests lights.
  domain: script
  author: BrendanxP, Adapted from Music Assistant
  homeassistant:
    min_version: 2024.6.0
  input:
    light_settings:
      name: Light Settings
      icon: mdi:lightbulb
      description: Configure light behavior
      input:
        default_area:
          name: Default Area
          description: Fallback if no target specified
          selector:
            area: {}
          default: {}
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      collapsed: true
      input:
        action_prompt:
          name: Action Prompt
          selector:
            text:
              multiline: true
          default: |
            MANDATORY. "action" = "turn_on", "turn_off", "toggle".
        target_type_prompt:
          name: Target Type Prompt
          selector:
            text:
              multiline: true
          default: |
            MANDATORY "target_type" = "entity" (single light), "area" (room), "floor" (upstairs).
            Pick ONE only. Examples: "Desk Brendan"=entity, "Living"=area, "Upstairs"=floor.
        target_name_prompt:
          name: Target Name Prompt
          selector:
            text:
              multiline: true
          default: |
            Exact HA name. "Desk Brendan", "Living Ceiling", "Nanoleaf Triangles", "Living", "Upstairs".
        brightness_pct_prompt:
          name: Brightness Prompt
          selector:
            text:
              multiline: true
          default: |
            brightness_pct 0-100. "half"=50, "dim"=30, "full"=100, "bright"=80. PRIORITY param.
        rgb_color_prompt:
          name: RGB Prompt
          selector:
            text:
              multiline: true
          default: |
            rgb_color "[R,G,B]" or "R,G,B". red="255,0,0", blue="0,0,255". RGB lights only.
        color_temp_kelvin_prompt:
          name: Color Temp Prompt
          selector:
            text:
              multiline: true
          default: |
            color_temp_kelvin 2000-6500K. "warm"=2700, "cool"=6500.
  addition_actions:
    name: Additional actions
    description: Actions after light command
    input:
      actions:
        selector:
          action: {}
        default: []

mode: parallel
max_exceeded: silent
description: Lights control script. Use parameters as described.
fields:
  action:
    selector:
      select:
        options: [turn_on, turn_off, toggle]
    name: Action
    description: !input action_prompt
    required: true
  target_type:
    selector:
      select:
        options: [entity, area, floor]
    name: Target Type
    description: !input target_type_prompt
    required: true
  target_name:
    selector:
      text: {}
    name: Target Name
    description: !input target_name_prompt
    required: true
  brightness_pct:
    selector:
      number:
        min: 0
        max: 100
    name: Brightness (%)
    description: !input brightness_pct_prompt
  rgb_color:
    selector:
      text: {}
    name: RGB Color
    description: !input rgb_color_prompt
  color_temp_kelvin:
    selector:
      number:
        min: 2000
        max: 6500
    name: Color Temp (K)
    description: !input color_temp_kelvin_prompt

sequence:
- variables:
    version: 20251229
    default_area: !input default_area
    light_data: '{% set lights = integration_entities("light") %}
      {% set light_names = lights | map("state_attr", "friendly_name") | list %}
      {% set ns = namespace(lights=[]) %}
      {% if target_type == "entity" %}
        {% if target_name in lights %}
          {% set ns.lights = ns.lights + [target_name] %}
        {% elif target_name in light_names %}
          {% set entity = lights | select("is_state_attr", "friendly_name", target_name) | first %}
          {% set ns.lights
