blueprint:
  name: LLM Script for Lights voice requests
  description: |
    This script controls ALL lights via voice. Use for ANY light request.
    
    Parameters: action (on/off/toggle), area/floor, brightness (0-100%), color_temp (kelvin).
    
    Use this script whenever user requests lights: "all lights living on", "dim bedroom", "warm upstairs off".
  domain: script  # ← FIXED: This was missing
  source_url: https://github.com/music-assistant/voice-support/blob/main/llm-script-blueprint/llm_voice_script.yaml
  author: Adapted for lights
  input:
    prompt_settings:
      name: LLM Prompts
      description: Fine-tune for your Qwen model
      input:
        action_prompt:
          name: Action Prompt
          default: '"action" must be "on", "off", or "toggle". Always required.'
        area_prompt:
          name: Area Prompt  
          default: 'Areas: "Living", "Bedroom", "Upstairs", "Downstairs", "Gaming, Office". Use area/floor from request.'
        brightness_prompt:
          name: Brightness Prompt
          default: 'Brightness 1-100 (%). "half"=50, "dim"=30, "full"=100. Optional.'
        color_temp_prompt:
          name: Color Temp Prompt
          default: '"warm"=2700, "cool"=6500, kelvin values 2000-6500K. Optional.'

fields:
  action:
    selector:
      select:
        options: [on, off, toggle]
    name: Action
    description: !input action_prompt
    required: true
  area:
    selector:
      area: {}
    name: Area/Floor
    description: !input area_prompt
  brightness:
    selector:
      number:
        min: 0
        max: 100
    name: Brightness (%)
    description: !input brightness_prompt
  color_temp:
    selector:
      number:
        min: 2000
        max: 6500
    name: Color Temp (Kelvin)
    description: !input color_temp_prompt

sequence:
  - service: "light.turn_{{ action }}"
    target:
      area_id: "{{ area | default([]) }}"
    data:
      brightness_pct: "{{ brightness | default(omit) }}"
      color_temp_kelvin: "{{ color_temp | default(omit) | int }}"
  - service: persistent_notification.create
    data:
      title: "Lights: {{ action }} {{ area | default('all') }}"
      message: "Brightness: {{ brightness | default('default') }}, Temp: {{ color_temp | default('default') }}K"

mode: parallel
max_exceeded: silent
