blueprint:
  name: LLM Script for Lights voice requests
  source_url: https://github.com/music-assistant/voice-support/blob/main/llm-script-blueprint/llm_voice_script.yaml
  description: |
    This script controls ALL lights via voice. Use for ANY light request.
    
    Parameters: action (on/off/toggle), area, brightness_pct (0-100), color_temp_kelvin (2000-6500).
    
    Use this script whenever user says "lights", "turn on/off", "dim", etc.
    
    Examples:
    - "all lights living on" → action="on", area="Living"
    - "dim gaming 50" → action="on", area="Gaming, Office", brightness_pct=50
    - "warm upstairs off" → action="off", area="Upstairs"
  domain: script
  author: Adapted from Music Assistant
  homeassistant:
    min_version: 2024.6.0
  input:
    light_settings:
      name: Light Settings
      icon: mdi:lightbulb
      description: Configure default light behavior
      input:
        default_area:
          name: Default Area
          description: Default area if none specified
          selector:
            area: {}
          default: {}
    prompt_settings:
      name: Prompt settings for LLM
      icon: mdi:robot
      description: Fine-tune prompts for Qwen
      collapsed: true
      input:
        action_prompt:
          name: Action Prompt
          default: '"action" must be "on", "off", or "toggle". Required for all light requests.'
        area_prompt:
          name: Area Prompt
          default: 'Areas from request: "Living", "Bedroom", "Upstairs", "Downstairs", "Gaming, Office", "Kitchen". Use satellite area if none specified.'
        brightness_prompt:
          name: Brightness Prompt
          default: 'brightness_pct: 0-100. "dim"=30, "half"=50, "full"=100, percentages.'
        color_temp_prompt:
          name: Color Temp Prompt
          default: 'color_temp_kelvin: 2000-6500K. "warm"=2700, "cool"=6500.'

fields:
  action:
    selector:
      select:
        options:
          - on
          - off
          - toggle
    name: Action
    description: !input action_prompt
    required: true
  area:
    selector:
      area: {}
    name: Area
    description: !input area_prompt
  brightness_pct:
    selector:
      number:
        min: 0
        max: 100
        step: 1
    name: Brightness (%)
    description: !input brightness_prompt
  color_temp_kelvin:
    selector:
      number:
        min: 2000
        max: 6500
        step: 100
    name: Color Temp (Kelvin)
    description: !input color_temp_prompt

sequence:
- variables:
    target_area: "{{ area | default(default_area | default([])) }}"
- service: "light.turn_{{ action }}"
  target:
    area_id: "{{ target_area }}"
  data:
    brightness_pct: "{{ brightness_pct | default(omit) }}"
    color_temp_kelvin: "{{ color_temp_kelvin | default(omit) }}"

mode: parallel
max_exceeded: silent
