blueprint:
  name: LLM Complete Lights Control
  description: |
    Complete light control: entity/area/floor + brightness/RGB/temp/effect/transition.
    
    MANDATORY: action + target_type + target_name
    OPTIONAL (PRIORITY order): brightness_pct > rgb_color > color_temp_kelvin > brightness_step_pct > effect > transition
    
    Use for ALL light requests. Dynamic - no fixed lists.
  domain: script
  input:
    prompt_settings:
      name: LLM Prompts
      input:
        action_prompt:
          default: '"action": "turn_on", "turn_off", or "toggle" - ALWAYS REQUIRED'
        target_type_prompt:
          default: |
            "target_type": "entity" (single light), "area" (room), "floor" (upstairs).
            EXCLUSIVE - pick ONE only. Never mix.
        brightness_prompt:
          default: |
            "brightness_pct": 0-100 PRIORITY. "half"=50, "dim"=30, "bright"=80, "+10%"=brightness_step_pct=10
  fields:
    action:
      selector: select
      options: [turn_on, turn_off, toggle]
      required: true
    target_type:
      selector: select
      options: [entity, area, floor]
      required: true
    target_name:
      selector: text:
      required: true
    brightness_pct:
      selector: number: {min: 0, max: 100}
    brightness_step_pct:
      selector: number: {min: -100, max: 100}
    rgb_color:
      selector: text:
    color_temp_kelvin:
      selector: number: {min: 2000, max: 6500}
    effect:
      selector: text:
    transition:
      selector: number: {min: 0, max: 60}

sequence:
- variables:
    target: >
      {% if target_type == 'entity' %}
        entity_id: "{{ target_name }}"
      {% elif target_type == 'area' %}
        area_id: "{{ target_name }}"
      {% else %}
        floor_id: "{{ target_name }}"
      {% endif %}
    data: >
      {% set d = {} %}
      {% if brightness_pct is number and brightness_pct > 0 %}{% set d = d | combine({'brightness_pct': brightness_pct|int}) %}{% endif %}
      {% if brightness_step_pct is number %}{% set d = d | combine({'brightness_step_pct': brightness_step_pct|int}) %}{% endif %}
      {% if rgb_color and rgb_color.strip() != '' %}{% set d = d | combine({'rgb_color': rgb_color.split(',')|map('trim')|map('int')|list}) %}{% endif %}
      {% if color_temp_kelvin is number %}{% set d = d | combine({'color_temp_kelvin': color_temp_kelvin|int}) %}{% endif %}
      {% if effect and effect.strip() != '' %}{% set d = d | combine({'effect': effect}) %}{% endif %}
      {% if transition is number %}{% set d = d | combine({'transition': transition}) %}{% endif %}
      {{ d if d else {} }}
- service: "light.{{ action }}"
  target: "{{ target }}"
  data: "{{ data }}"
mode: parallel
